version: '3.8'

services:

    frontend:
      image: frontend
      ports:
        - "5000:5000"
      container_name: frontend

    backend:
      image: backend
      ports:
        - "8080:8080"
      container_name: backend
      environment:
        - REDIS_HOST=redis
        - ENV REQUEST_ORIGIN=http://192.168.10.40:5000
      restart: unless-stopped
      
    redis:
      image: redis
      container_name: redis