version: '3.8'

services:

    frontend:
      image: frontend
      container_name: frontend
      # port 5000

    backend:
      image: backend
      container_name: backend
      environment:
        - REDIS_HOST=redis
        - REQUEST_ORIGIN=http://192.168.10.40:5000
        - POSTGRES_HOST=db
        - POSTGRES_USER=backend_user
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DATABASE=backend_db
      restart: unless-stopped
      # port 8080

    redis:
      image: redis
      container_name: redis

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=backend_user
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=backend_db
      container_name: db_redmine
      volumes:
        - ./database:/var/lib/postgresql/data

    nginx:
      image: nginx
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
      ports:
        - 80:80
